extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	var cnum = Cnum.new(1, 1)
	var cnum2 = Cnum.new(5, -4)
	print("Complex number 1:")
	print(cnum)
	print("Complex number 2:")
	print(cnum2)
	print("Addition:")
	print(ComplexMaths.add(cnum, cnum2))
	print("Subtraction:")
	print(ComplexMaths.sub(cnum, cnum2))
	print("Multiplication")
	print(ComplexMaths.mult(cnum, cnum2))
	print("Division:")
	print(ComplexMaths.divide(cnum, cnum2))
	print("Reciprocal:")
	print(ComplexMaths.recip(cnum2))
	print("Conjugation:")
	print(ComplexMaths.conj(cnum2))
	print("Square root:")
	print(ComplexMaths.csqrt(cnum2))
	print("Exponential:")
	print(ComplexMaths.cexp(cnum2))
	print("Natural log:")
	print(ComplexMaths.ln(cnum2))
	
	var eye = ComplexAlgebra.eye(6)
	eye.set_index(Cnum.new(2.0, -4.0), 4, 1)
	var vec = ComplexAlgebra.random_vector(6)
	var result = ComplexAlgebra.tdot(vec, eye)
	eye.printm()
	vec.printm()
	result.printm()
